# Generated by Django 3.1.13 on 2021-08-03 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20210802_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydetails',
            name='list_of_registered_areas',
            field=models.CharField(default='Dembe, Amtoukoui, Hamama', max_length=1500),
            preserve_default=False,
        ),
    ]
