# Generated by Django 3.1.13 on 2021-08-04 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_companydetails_list_of_registered_areas'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorMesage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_message', models.CharField(max_length=500)),
                ('error_message', models.CharField(max_length=500)),
                ('slug', models.SlugField(blank=True, max_length=5000, null=True, unique=True)),
                ('added_on_date_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
