# Generated by Django 3.1.13 on 2021-08-28 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_clientproductcategory_reference_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemuser',
            name='employee_ranking',
            field=models.IntegerField(default=0),
        ),
    ]
